# Generated by Django 5.0.1 on 2024-08-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
