# Generated by Django 5.0.1 on 2024-08-28 17:09
from django.db import migrations

def populate_origin_destination(apps, schema_editor):
    Route = apps.get_model('flight', 'Route')
    Airport = apps.get_model('flight', 'Airport')

    for route in Route.objects.all():
        source_location = Airport.objects.get(airport_id=route.source_airport_id)
        route.origin = f"{source_location.city}, {source_location.country}"
        
        destination_location = Airport.objects.get(airport_id=route.destination_airport_id)
        route.destination = f"{destination_location.city}, {destination_location.country}"
        
        route.save()

class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_route_destination_route_origin'),
    ]

    operations = [
        migrations.RunPython(populate_origin_destination),
    ]
